services:
  backend:
    build:
      target: development
    image: pick-vegetables
    volumes:
      - ./src:/usr/app/src
    ports:
      - "5000:5000"
    env_file: .env
    depends_on:
      - db

  db:
    image: postgres:16.2
    restart: always
    env_file: .env